# Generated by Django 5.0.3 on 2024-03-28 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_Monday', models.BooleanField(default=False, verbose_name='В понедельник')),
                ('on_Tuesday', models.BooleanField(default=False, verbose_name='Во вторник')),
                ('on_Wednesday', models.BooleanField(default=False, verbose_name='В среду')),
                ('on_Thursday', models.BooleanField(default=False, verbose_name='В четверг')),
                ('on_Friday', models.BooleanField(default=False, verbose_name='В пятницу')),
                ('on_Saturday', models.BooleanField(default=False, verbose_name='В субботу')),
                ('on_Sunday', models.BooleanField(default=False, verbose_name='В воскресенье')),
            ],
        ),
        migrations.CreateModel(
            name='GoodAddiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Место привычки')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время привычки')),
                ('proprietor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Addiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Место привычки')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время привычки')),
                ('prize', models.TextField(blank=True, verbose_name='Награда')),
                ('run_time', models.IntegerField(default=120, verbose_name='Длительность в секундах')),
                ('is_public', models.BooleanField(verbose_name='Публичная привычка')),
                ('proprietor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('good_addiction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.goodaddiction', verbose_name='Связанная полезная привычка')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.periodicity', verbose_name='Периодичность')),
            ],
        ),
    ]
