# Generated by Django 5.0.3 on 2024-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_addiction_activity_name_alter_addiction_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodaddiction',
            name='activity_name',
            field=models.TextField(default='балду гоняю', verbose_name='Что делаю'),
        ),
        migrations.AlterField(
            model_name='goodaddiction',
            name='location',
            field=models.CharField(default='Где-то', max_length=50, verbose_name='Где делаю'),
        ),
        migrations.AlterField(
            model_name='goodaddiction',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Когда делаю'),
        ),
    ]
