# Generated by Django 5.0.3 on 2024-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_periodicity_proprietor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addiction',
            options={'verbose_name': 'Полезная привычка', 'verbose_name_plural': 'Полезные привычки'},
        ),
        migrations.AlterModelOptions(
            name='goodaddiction',
            options={'verbose_name': 'Приятная привычка', 'verbose_name_plural': 'Приятные привычки'},
        ),
        migrations.AlterModelOptions(
            name='periodicity',
            options={'verbose_name': 'Периодичность', 'verbose_name_plural': 'Периодичности'},
        ),
        migrations.AlterField(
            model_name='addiction',
            name='prize',
            field=models.TextField(blank=True, null=True, verbose_name='Награда'),
        ),
    ]
