# Generated by Django 5.0.3 on 2024-03-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_addiction_options_alter_goodaddiction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodaddiction',
            name='proprietor',
        ),
        migrations.RemoveField(
            model_name='periodicity',
            name='proprietor',
        ),
        migrations.AlterField(
            model_name='addiction',
            name='good_addiction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.goodaddiction', verbose_name='Связанная полезная привычка'),
        ),
        migrations.AlterField(
            model_name='addiction',
            name='prize',
            field=models.TextField(blank=True, default=None, verbose_name='Награда'),
        ),
    ]
