# Generated by Django 5.0.3 on 2024-04-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_addiction_prize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodAddiction',
            new_name='NiceAddiction',
        ),
    ]
