# Generated by Django 5.0.3 on 2024-04-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_goodaddiction_niceaddiction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addiction',
            old_name='good_addiction',
            new_name='nice_addiction',
        ),
    ]
