# Generated by Django 5.0.3 on 2024-04-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_good_addiction_addiction_nice_addiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addiction',
            name='nice_addiction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.niceaddiction', verbose_name='Связанная полезная привычка'),
        ),
    ]
